# Generated by Django 3.2.25 on 2025-08-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
    ]
