# Generated by Django 3.2.25 on 2025-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.CharField(default='', max_length=254),
        ),
    ]
