# Generated by Django 3.2.25 on 2025-08-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='test',
        ),
    ]
